export const ENV = 'prod';
export const X_THEME = 'ChffrPlus'

export const Params = {
    KEY_IS_METRIC: 'IsMetric',
    KEY_RECORD_FRONT: 'RecordFront',
    KEY_IS_REAR_VIEW: 'IsRearViewMirror',
    KEY_CALIBRATION_PARAMS: 'CalibrationParams',
    KEY_CLOUD_CALIBRATION: 'CloudCalibration',
    KEY_DONGLE_ID: 'DongleId',
    KEY_ACCEPTED_TERMS_VERSION: 'HasAcceptedTerms',
    KEY_DO_UNINSTALL: 'DoUninstall',
    KEY_HAS_COMPLETED_SETUP: 'HasCompletedSetup',
    KEY_IS_PASSIVE: 'Passive',
    KEY_LATEST_TRAINING_VERSION: 'TrainingVersion',
    KEY_COMPLETED_TRAINING_VERSION: 'CompletedTrainingVersion',
    KEY_LATEST_TERMS_VERSION: 'TermsVersion',
    KEY_IS_GEOFENCE_ENABLED: 'IsGeofenceEnabled',
    KEY_HAS_LONGITUDINAL_CONTROL: 'LongitudinalControl',
    KEY_LIMIT_SET_SPEED: 'LimitSetSpeed',
    KEY_SPEED_LIMIT_OFFSET: 'SpeedLimitOffset',
    KEY_LIVE_PARAMETERS: 'LiveParameters',
    KEY_GITHUB_SSH_KEYS: 'GithubSshKeys',
    KEY_RELEASE_NOTES: 'ReleaseNotes',
    KEY_IS_UPDATE_AVAILABLE: 'UpdateAvailable',
    KEY_OPENPILOT_ENABLED: 'OpenpilotEnabledToggle',
    KEY_OFFROAD_CHARGE_DISABLED: 'Offroad_ChargeDisabled',
    KEY_OFFROAD_TEMPERATURE_TOO_HIGH: 'Offroad_TemperatureTooHigh',
    KEY_OFFROAD_CONNECTIVITY_NEEDED_PROMPT: 'Offroad_ConnectivityNeededPrompt',
    KEY_OFFROAD_CONNECTIVITY_NEEDED: 'Offroad_ConnectivityNeeded',
    KEY_OFFROAD_PANDA_FIRMWARE_MISMATCH: 'Offroad_PandaFirmwareMismatch',
    KEY_OFFROAD_INVALID_TIME: 'Offroad_InvalidTime',
    KEY_OFFROAD_IS_TAKING_SNAPSHOT: 'Offroad_IsTakingSnapshot',
    KEY_COMMUNITY_FEATURES: 'CommunityFeaturesToggle',
    KEY_LANE_DEPARTURE_WARNING_ENABLED: 'IsLdwEnabled',
    KEY_LANE_CHANGE_ENABLED: 'LaneChangeEnabled',
    KEY_IS_DRIVER_VIEW_ENABLED: 'IsDriverViewEnabled',
    KEY_IS_RHD: 'IsRHD',
    KEY_IS_OFFROAD: 'IsOffroad',
};
